# Generated by Django 5.0.6 on 2024-06-20 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="FirstName",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="Id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="LastName",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="Password",
            field=models.CharField(max_length=20),
        ),
    ]
