# Generated by Django 5.0.6 on 2024-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_user_id_alter_user_email_alter_user_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Password",
            field=models.CharField(max_length=200),
        ),
    ]
